# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-10 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20170410_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='currently_employed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
