# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20170410_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='currently_employed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
