# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-18 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20170410_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='available_date',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='city',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='currently_employed',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='home_number',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='latest_qualification',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='pay_range_expectation',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='previous_company',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='state',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='total_experience',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='year_passed_out',
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='first_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='mobile_number',
            field=models.CharField(max_length=60, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='position_sought',
            field=models.CharField(choices=[('', 'Select'), ('Development', 'Development'), ('Testing', 'Testing'), ('Admin', 'Admin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(blank=True, default='Apply', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='title',
            field=models.CharField(blank=True, choices=[('', 'Select----'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss')], default='Mr', max_length=10, null=True),
        ),
    ]
