# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20170418_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationStatus',
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='position_sought',
            field=models.CharField(choices=[('Development', 'Development'), ('Testing', 'Testing'), ('Admin', 'Admin')], default='Development', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss')], default='Mr', max_length=10, null=True),
        ),
    ]
